const countries = [
  { id: "1", name: "India" },
  { id: "2", name: "USA" },
  { id: "3", name: "Canada" },
  { id: "4", name: "Australia" },
];

const states = [
  { id: "1", countryId: "1", name: "Delhi" },
  { id: "2", countryId: "1", name: "Maharashtra" },
  { id: "3", countryId: "1", name: "Karnataka" },
  { id: "4", countryId: "2", name: "California" },
  { id: "5", countryId: "2", name: "Texas" },
  { id: "6", countryId: "2", name: "Florida" },
  { id: "7", countryId: "3", name: "Ontario" },
  { id: "8", countryId: "3", name: "Quebec" },
  { id: "9", countryId: "3", name: "British Columbia" },
  { id: "10", countryId: "4", name: "New South Wales" },
  { id: "11", countryId: "4", name: "Victoria" },
  { id: "12", countryId: "4", name: "Queensland" },
];

const cities = [
  { id: "1", stateId: "1", name: "New Delhi" },
  { id: "2", stateId: "1", name: "South Delhi" },
  { id: "3", stateId: "1", name: "Dwarka" },
  { id: "4", stateId: "2", name: "Mumbai" },
  { id: "5", stateId: "2", name: "Pune" },
  { id: "6", stateId: "2", name: "Nagpur" },
  { id: "7", stateId: "3", name: "Bengaluru" },
  { id: "8", stateId: "3", name: "Mysuru" },
  { id: "9", stateId: "3", name: "Hubli" },
  { id: "10", stateId: "4", name: "Los Angeles" },
  { id: "11", stateId: "4", name: "San Francisco" },
  { id: "12", stateId: "4", name: "San Diego" },
  { id: "13", stateId: "5", name: "Houston" },
  { id: "14", stateId: "5", name: "Dallas" },
  { id: "15", stateId: "5", name: "Austin" },
  { id: "16", stateId: "6", name: "Miami" },
  { id: "17", stateId: "6", name: "Orlando" },
  { id: "18", stateId: "6", name: "Tampa" },
  { id: "19", stateId: "7", name: "Toronto" },
  { id: "20", stateId: "7", name: "Ottawa" },
  { id: "21", stateId: "7", name: "Mississauga" },
  { id: "22", stateId: "8", name: "Montreal" },
  { id: "23", stateId: "8", name: "Quebec City" },
  { id: "24", stateId: "8", name: "Laval" },
  { id: "25", stateId: "9", name: "Vancouver" },
  { id: "26", stateId: "9", name: "Victoria" },
  { id: "27", stateId: "9", name: "Surrey" },
  { id: "28", stateId: "10", name: "Sydney" },
  { id: "29", stateId: "10", name: "Newcastle" },
  { id: "30", stateId: "10", name: "Wollongong" },
  { id: "31", stateId: "11", name: "Melbourne" },
  { id: "32", stateId: "11", name: "Geelong" },
  { id: "33", stateId: "11", name: "Ballarat" },
  { id: "34", stateId: "12", name: "Brisbane" },
  { id: "35", stateId: "12", name: "Gold Coast" },
  { id: "36", stateId: "12", name: "Townsville" },
];
export { countries, states, cities };
